name: CI

on: [push, pull_request]

jobs:
  check:
    name: ${{ matrix.arch }}-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [powerpc]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install build-essential flex bison libelf-dev libssl-dev qemu-system-ppc
    - name: Build & Test
      run: make
    - name: Test
      run: ./sample && uname -a
