on: [push, pull_request]

jobs:
  s390x_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu s390x
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: s390x
          distro: fedora_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            dnf install bison flex cmake make git gcc-c++ elfutils-libelf-devel zlib-devel llvm-devel clang-devel bcc-devel systemtap-sdt-devel binutils-devel -y
            echo ::set-output name=uname::$(uname -a)
            mkdir build-dir && cd build-dir
            git clone https://github.com/iovisor/bpftrace.git
            cd bpftrace
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make -j2
            cd tests
            ./runtime-tests.sh

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
